baseurl: /website
url: https://studentrobotics.org
permalink: /news/:year-:month-:day-:title/

title: Student Robotics
description: >
  Student Robotics is an exciting annual competition challenging people aged
  16-18 to assemble a team and build fully autonomous robots.

markdown: kramdown
collections:
  - events

gems:
  - jekyll-paginate

links:
  compete: //docs.google.com/forms/d/1Ryg2cfAxfwMOBnT01aj-fzsp51F3B182S5e53ye8aMw/viewform
  volunteer: //docs.google.com/forms/d/1MIGf3P30dw0QAtP8OkxK2v7VRDEAN_54JoZHCVMbqDY/viewform

navigation:
  - about
  - compete
  - volunteer

emails:
  teams: teams@studentrobotics.org
  fundraising: fundraising@studentrobotics.org
  volunteers: volunteer-recruitment@studentrobotics.org
  pr: pr@studentrobotics.org
  info: info@studentrobotics.org

social:
  facebook-official: //facebook.com/StudentRobotics
  twitter: //twitter.com/studentrobotics
  youtube: //youtube.com/StudentRobotics
  github: //github.com/srobo

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - _env/
  - _docs/
  - vendor/

paginate: 3
paginate_path: "/news/:num/"