title: Student Robotics
baseurl: /website
url: http://studentrobotics.org

description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

links:
  compete: //docs.google.com/forms/d/1Ryg2cfAxfwMOBnT01aj-fzsp51F3B182S5e53ye8aMw/viewform
  volunteer: //docs.google.com/forms/d/1MIGf3P30dw0QAtP8OkxK2v7VRDEAN_54JoZHCVMbqDY/viewform

navigation:
  - about.html
  - compete.html
  - volunteer.html

emails:
  teams: teams@studentrobotics.org
  fundraising: fundraising@studentrobotics.org
  volunteers: volunteer-recruitment@studentrobotics.org
  pr: pr@studentrobotics.org
  info: info@studentrobotics.org

social:
  facebook-official: //facebook.com/StudentRobotics
  twitter: //twitter.com/studentrobotics
  youtube: //youtube.com/StudentRobotics
  github: //github.com/srobo

exclude:
  - docs
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock

markdown: kramdown

collections:
  - events
